services:
  lanchonete-preparo-db:
    image: postgres:16.0
    restart: always
    container_name: lanchonete-preparo-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    networks:
      - default

  preparo-service:
    build: .
    container_name: lanchonete-preparo
    depends_on:
      - lanchonete-preparo-db
    volumes:
      - m2-repo:/usr/share/maven
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: lanchonete-preparo-db
      POSTGRES_PORT: 5432
      HTTP_PORT: 8080

      NATS_URL: nats://nats:4222
      NATS_APP_NAME: pedido
      NOVO_PREPARO_TOPIC: pedido.novo-preparo

    networks:
      - default
      - lanchonete_lanchonete
    ports:
      - "8082:8080"

    command: ["prod"]

volumes:
  m2-repo:

networks:
  lanchonete_lanchonete:
    external: true
